insert into parametro values(default, '', 'inicio.jpg', 'INICIO', true);
insert into parametro values(default, '', 'fondoiniciosesion.jpg', 'FONDOINICIOSESION', true);
insert into parametro values(default, '', 'Bienvenido a Gym-Up!_Gestionar tu gimnasio nunca había sido tan facil', 'CONCEPTOSLIDE', true);
insert into parametro values(default, '', 'Centralización_de la información de tus usuarios', 'CONCEPTOSLIDE', true);
insert into parametro values(default, '', 'Muestrale la evolución_del plan de entrenamiento a tus clientes', 'CONCEPTOSLIDE', true);
insert into parametro values(default, '', 'Reduce los tiempos_en la gestión de tus usuarios', 'CONCEPTOSLIDE', true);
insert into parametro values(default, 'KILOGRAMOS', 'KG', 'MEDIDAPESO', true);
insert into parametro values(default, 'LIBRAS', 'LB', 'MEDIDAPESO', true);
insert into parametro values(default, 'SEGUNDOS', 'SEG', 'MEDIDATIEMPO', true);
insert into parametro values(default, 'MINUTOS', 'MIN', 'MEDIDATIEMPO', true);
insert into parametro values(default, 'HORAS', 'HORAS', 'MEDIDATIEMPO', true);