CREATE TABLE empresa(
   id                   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   nombre               varchar NOT NULL,
   endpoint             varchar NOT NULL,
   activo               boolean NOT NULL,
   PRIMARY KEY (id)
);