CREATE TABLE mensaje(
   id                   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
   nombre               varchar NOT NULL,
   celular              varchar NOT NULL,
   correo               varchar NOT NULL,
   observacion          varchar NOT NULL,
   fecha_creacion       timestamp without time zone NOT NULL,
   activo               boolean NOT NULL,
   PRIMARY KEY (id)
);